### ISSUE TITLE
Thursday exercise

### ISSUE THREAD

**Issue by vinh-tranhuu** [101121-VA-Java/Hannah-Wallaker#2]
What would be the value of getFoodTypes() here?
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L4

This would be a String array rather than a String, I'm a little confused by the rest of the sentence
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L7

What is printed out here?
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L10

This returns a string array rather than a String
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L14

Little confused by this statement
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L15

This also returns a string array
https://github.com/101121-VA-Java/Hannah-Wallaker/blob/988a69ff5dc7d215c8ba05e8fc06e97b855a3abc/Week2/thursday.java#L19

Some of the explanation was a bit confusing, otherwise the logic was sound.
Be careful of String vs String array

**Comment by hannahwallaker** [comment]
I do appreciate these code explanation assignments and appreciate you taking the time to correct them!
